# This is a basic workflow to help you get started with Actions

name: Update CI relability

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#  schedule:
#    - cron: '0 0 * * *'
  
jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm i -g node-core-utils
    - run: ncu-config --global set jenkins_token ${{ secrets.JENKINS_TOKEN }}
    - run: ncu-config --global set token ${{ secrets.USER_TOKEN }}
    - run: ncu-config --global set username ${{ secrets.USER_NAME }}
    - run: ncu-ci walk pr --stats=true --markdown $PWD/results.md
    - run: |
        body=`cat results.md | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'`
        title_date=$(date +%Y-%m-%d)
        curl --request POST \
        --url https://api.github.com/repos/${GITHUB_REPOSITORY}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data "{
          \"title\": \"CI Relability ${title_date}\",
          \"body\": ${body}
          }"
