# This is a basic workflow to help you get started with Actions

name: Update CI relability

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch
  
jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm i -g node-core-utils
    - run: ncu-config --global set jenkins_token ${{ secrets.JENKINS_TOKEN }}
    - run: ncu-ci walk pr --stats=true --markdown results.md
    - run: |
        body=`cat results.md`
        title_date=$(date + '%Y-%m-%d')
        curl -u $GITHUB_TOKEN:x-oauth-basic https://api.github.com/repos/$GITHUB_REPOSITORY/issues -d '{
          "title": "CI Relability ${date}",
          "body": "${body@Q}"
        }' 
